# invit config file (yaml)
patch_size: 4 # Input image size: 32x32 -> 8x8 patches
hidden_size: 48
num_hidden_layers: 4
num_attention_heads: 4
intermediate_size: 192 # 4 * hidden_size
hidden_dropout_prob: 0.0
attention_probs_dropout_prob: 0.0 
initializer_range: 0.02 
image_size: 32
num_classes: 10 # num_classes of CIFAR10
num_channels: 3
qkv_bias: true
use_faster_attention: true
batch_size: 256
epochs: 100
lr: 0.01
save_model_every: 0